### ISSUE TITLE
Crash due to invalid BankSignitures, caused by a locale issue

### ISSUE THREAD

**Issue by GreenSkull8** [cheatfreak47/NMSDecompressinator#8]
I did it 2 times. It gives this error at startup. I tried removing all the mods but its still same so i know its not mods. After trying the first time, i fixed files with steam verify. Then tried again to make sure but its still same error. I have +200gb free space on my SSD too. I even tried copying "PackedFileBackup" folder's backup files but it gives another error (I found it online "https://preview.redd.it/crash-on-start-up-v0-dqy5jmvb6djc1.png?width=696&format=png&auto=webp&s=69e948bb1fe8824d47b3b04a11f67cb167f3ffff")

![Screenshot_1](https://github.com/user-attachments/assets/0116a0df-3ae2-4f17-b6d1-429e80d19a35)

[BankSignatures.zip](https://github.com/user-attachments/files/16516557/BankSignatures.zip)

**Comment by cheatfreak47** [comment]
If the game does not boot stock after running a Steam verify then you have a problem completely unrelated to my script.
I suggest completely deleting the No Man's Sky folder and then running a verify again.

Something strange is also going on in your BankSignitures, all your filenames with the letter I in it are showing up as ?s, which I have no idea what the cause of that might be.

**Comment by cheatfreak47** [comment]
I only have two guesses as to what could cause this:
1. Your system has some sort of untested locale or filesystem wreaking havoc that I could never have possibly accounted for. (I have no easy way of figuring this out without you giving me detailed system information.)
2. You are experiencing some sort of hardware failure, and you just don't know it yet.

If you'd rather, we could try and debug this over Discord instead so I can get some further details, but I sincerely doubt there's any problem that is caused by the script itself. If you want to, join the official No Man's Sky Discord and ping @cheatfreak in #modding.

**Comment by GreenSkull8** [comment]
Hi, thanks for the info but my game does work when i use steam verify. It only breaks after the script. I have English as main language for my PC but im Turk so there is a second language which is Turkish on my system. I guess that's the problem because in our language there is different letters like big i "İ" and small I "ı" that might be the problem. And the funny thing with windows is that after format my first language was Turkish, so when i changed to English some of the things duplicated like "denetim masası" in english its "control panel". When i type any one of them the control panel pops up. So i can use both language to find some of the things but not all of them.

**Comment by cheatfreak47** [comment]
Well from the info provided It _looks_ like the problem is your Turkish locale with specifically NMSResign, so this is very likely a bug in the upstream tool NMSResign, but I need to A-B test it with you, and also verify the bug isn't in PSARC or some other part of the process (eg- PSARC is extracting the normal filenames to bad file names and the archives are bad or whatever).

Made an issue on the NMSResign tracker for this too, but for now we'll keep discussion on this issue thread.
#https://github.com/cheatfreak47/NMSResign/issues/1

**Comment by cheatfreak47** [comment]
@GreenSkull8 if you could hop back on the discord and help me A-B test a possible fix, that would be fine as well.

**Comment by cheatfreak47** [comment]
#https://github.com/cheatfreak47/NMSResign/issues/1 is confirmed as the cause by testing with @GreenSkull8, so this issue was invalid- the problem comes from upstream.
